version: "3.6"
services:
  db:
    image: mysql:latest
    ports: 
      - 3307:3306
    networks:
      - employee-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - my-db:/var/lib/mysql
networks:
  employee-mysql:
    driver: bridge
# Names our volume
volumes:
  my-db:
  
# volume to persist db data 
# network to make services connect with db
# default root username is root