apiVersion: v1
kind: Service
metadata:
  name: assignment-user-service
spec:
  selector:
    app: assignment-user
  ports:
    - protocol: TCP # default clusterIP
      port: 80
      targetPort: 8080