apiVersion: v1
kind: Service
metadata:
  name: assignment-order-service
spec:
  selector:
    app: assignment-order
  ports:
    - protocol: TCP # default clusterIP
      port: 80
      targetPort: 8080