apiVersion: v1
kind: Service
metadata:
  name: assignment-aggregator-service
spec:
  selector:
    app: assignment-aggregator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
